default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: swishjam_dev

test:
  <<: *default
  database: database_test

production:
  <<: *default
  database: database_production
  username: database
  password: <%= ENV['DATABASE_DATABASE_PASSWORD'] %>
