default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  prepared_statements: false

development:
  transactional:
    <<: *default
    database: swishjam_dev
  clickhouse:
    adapter: clickhouse
    database: swishjam_analytics_dev
    host: localhost
    port: 8123
    username: default
    debug: true

test:
  transactional:
    <<: *default
    database: swishjam_test
  clickhouse:
    adapter: clickhouse
    database: swishjam_analytics_test
    host: localhost
    port: 8123
    username: default
    debug: true

production:
  transactional:
    <<: *default
    url: <%= ENV['POSTGRES_DB_CONNECTION_POOLING_STRING'] %>
  clickhouse:
    adapter: clickhouse
    database: swishjam_analytics
    host: <%= ENV['CLICKHOUSE_DB_HOST'] %>
    port: 8443
    username: <%= ENV['CLICKHOUSE_DB_USERNAME'] %>
    password: <%= ENV['CLICKHOUSE_DB_PASSWORD'] %>
    ssl: true
    # debug: false


porter app run swishjam-prod -- rake db:migrate

porter app run swishjam-prod -- rake data_migrations:temporary:new_ingestion_data_migration