default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  transactional:
    <<: *default
    database: swishjam_dev
  clickhouse:
    adapter: clickhouse
    database: swishjam_analytics_dev
    host: localhost
    port: 8123
    username: default
    debug: true
    # ssl: true
    # migrations_paths: db/clickhouse
    # cluster_name: 'some_cluster_name'
    # replica_name: '{replica_macros_name}'

test:
  transactional:
    <<: *default
    database: swishjam_test
  clickhouse:
    adapter: clickhouse
    database: swishjam_analytics_test
    host: localhost
    port: 8123
    username: default
    debug: true

production:
  <<: *default
  database: swishjam
  username: database
  password: <%= ENV['DATABASE_DATABASE_PASSWORD'] %>
