---
:concurrency: <%= ENV.fetch('INGESTION_SIDEKIQ_CONCURRENCY', 5) %>
:max_retries: 10
# TODO: should we use weights instead here? (ie: [[automations_queue, 2], [click_house_writer_queue, 1], [format_events_queue, 1]])
:queues:
  - automations_queue
  - click_house_writer_queue
  - format_events_queue
:scheduler:
  :schedule:
    clickhouse_writer_queue:
      cron: "*/1 * * * *" # every minute
      class: IngestionJobs::WriteToClickHouseFromIngestionQueues