---
:concurrency: 5

:scheduler:
  :schedule:
    ingest_events_queue:
      cron: "*/1 * * * *" # every minute
      class: IngestJobs::Events
    ingest_user_identifies_queue:
      cron: "*/10 * * * *"
      class: IngestJobs::UserIdentifies
    ingest_organization_identifies_queue:
      cron: "*/10 * * * *"
      class: IngestJobs::OrganizationIdentifies
    ingest_user_profile_click_house_replication_queue:
      cron: "*/10 * * * *"
      class: IngestJobs::UserProfileClickHouseReplication
    stripe_data_daily_sync:
      cron: "0 8 * * *" # every day @ 8am UTC
      class: DataSyncJobs::Stripe
    daily_reports:
      cron: "0 16 * * *" # every day @ 4pm UTC (8 am PST)
      class: DailyReportsBatchRunnerJob
