---
:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 5) %>
:max_retries: 10

:scheduler:
  :schedule:
    update_cohort_profile_tags:
      cron: "0 * * * *" # at the top of every hour
      class: UpdateCohortProfileTagsJob
    stripe_data_daily_sync:
      cron: "0 8 * * *" # every day @ 8am UTC
      class: DataSyncJobs::Stripe
    daily_reports:
      cron: "0 16 * * *" # every day @ 4pm UTC (8 am PST)
      class: ReportJobs::DailyRunner
    weekly_reports:
      cron: "0 16 * * MON" # every week on Monday @ 4pm UTC (8 am PST)
      class: ReportJobs::WeeklyRunner
    monthly_reports:
      cron: "0 16 1 * *" # every month on the 1st @ 4pm UTC (8 am PST)
      class: ReportJobs::MonthlyRunner
    data_cleanup:
      cron: "0 7 * * *" # every day @ 12am PST
      class: DataCleanupJob
    # event_trigger_summaries:
    #   cron: "0 16 * * MON" # every week on Monday @ 8am PST
    #   class: EventTriggerSummariesJob
