---
:concurrency: 5

:scheduler:
  :schedule:
    ingest_events_queue:
      cron: "*/1 * * * *" # every minute
      class: IngestJobs::Events
    ingest_user_identifies_queue:
      cron: "*/10 * * * *"
      class: IngestJobs::UserIdentifies
    ingest_organization_profiles_queue:
      cron: "*/10 * * * *"
      class: IngestJobs::OrganizationProfiles
    ingest_user_profile_click_house_replication_queue:
      cron: "*/10 * * * *"
      class: IngestJobs::UserProfileClickHouseReplication
    ingest_organization_profile_click_house_replication_queue:
      cron: "*/10 * * * *"
      class: IngestJobs::OrganizationProfileClickHouseReplication
    ingest_user_profiles_from_events_queue:
      cron: "*/10 * * * *"
      class: IngestJobs::UserProfilesFromEvents
    stripe_data_daily_sync:
      cron: "0 8 * * *" # every day @ 8am UTC
      class: DataSyncJobs::Stripe
    daily_reports:
      cron: "0 16 * * *" # every day @ 4pm UTC (8 am PST)
      class: ReportJobs::DailyRunner
    weekly_reports:
      cron: "0 16 * * MON" # every week on Monday @ 4pm UTC (8 am PST)
      class: ReportJobs::WeeklyRunner
    monthly_reports:
      cron: "0 16 1 * *" # every month on the 1st @ 4pm UTC (8 am PST)
      class: ReportJobs::MonthlyRunner
    data_cleanup:
      cron: "0 7 * * *" # every day @ 12am PST
      class: DataCleanupJob
    event_trigger_summaries:
      cron: "0 16 * * MON" # every week on Monday @ 8am PST
      class: EventTriggerSummariesJob
