---
:concurrency: 5

:scheduler:
  :schedule:
    format_events_queue:
      cron: "*/1 * * * *" # every minute
      class: IngestJobs::Events
    clickhouse_writer_queue:
      cron: "*/1 * * * *" # every minute
      class: IngestJobs::ClickhouseWriter
    stripe_data_daily_sync:
      cron: "0 8 * * *" # every day @ 8am UTC
      class: DataSyncJobs::Stripe
    daily_reports:
      cron: "0 16 * * *" # every day @ 4pm UTC (8 am PST)
      class: DailyReportsBatchRunnerJob
    data_cleanup:
      cron: "0 7 * * *" # every day @ 12am PST
      class: DataCleanupJob
    event_trigger_summaries:
      cron: "0 16 * * MON" # every week on Monday @ 8am PST
      class: EventTriggerSummariesJob
