version: '3'
services:
  web:
    build: .
    ports:
      - "4242:4242"
    depends_on:
      - db
  db:
    image: postgres:13 # Use the official PostgreSQL image
    environment:
      POSTGRES_DB: myapp_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret