source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.2'

gem 'rails', '~> 6.1.7', '>= 6.1.7.4'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'bootsnap', '>= 1.4.4', require: false

# disables console warnings with already initialized constant?
# https://stackoverflow.com/questions/67773514/getting-warning-already-initialized-constant-on-assets-precompile-at-the-time
gem 'net-http' 

gem 'active_model_serializers'
gem 'bcrypt'
gem 'clickhouse-activerecord'
gem 'colorize'
gem 'connection_pool'
gem 'dotenv'
gem 'faker'
gem 'geocoder'
gem 'googleauth'
gem 'google-apis-searchconsole_v1', '~> 0.1'
gem 'google-apis-oauth2_v2'
gem 'groupdate'
gem 'jwt'
gem 'kaminari'
gem 'peopledatalabs'
gem 'rack-cors'
gem 'redis'
gem 'resend'
gem 'sentry-rails'
gem 'sentry-ruby'
gem 'sentry-sidekiq'
gem 'sidekiq', '~> 6.5'
gem 'sidekiq-failures'
gem 'sidekiq-scheduler'
gem 'stripe'
gem "tty-prompt"
gem 'tty-progressbar'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :test do
  gem 'rspec'
  gem 'factory_bot_rails'
  gem 'database_cleaner'
  gem 'simplecov'
end
