# frozen_string_literal: true

ruby "3.1.0"

source "https://rubygems.org"
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sidekiq", "~> 7.1.2"
gem 'httparty'
gem 'dotenv'
gem 'byebug'
gem 'google-cloud-bigquery'