export const CODES_TO_NAME = {
  'ec2-us-east-1': 'Virginia, USA',
  'gce-us-west3': 'Salt Lake City, Utah, USA',
  'ec2-us-west-1': 'California, USA',
  'ec2-ca-central-1': 'Toronto, Canada',
  'ec2-sa-east-1': 'Sao Paulo, Brazil',
  'ec2-eu-west-1': 'Ireland',
  'London_EC2': 'London, UK',
  'ec2-eu-west-3': 'Paris, France',
  'gce-europe-west4': 'Amsterdam, NL',
  'ec2-eu-central-1': 'Frankfurt, Germany',
  'ec2-eu-south-1': 'Milan, Italy',
  'ec2-eu-north-1': 'Stockholm, Sweden',
  'ec2-af-south-1': 'Cape Town, South Africa',
  'ec2-me-south-1': 'Bahrain',
  'ap-south-1': 'Mumbai, India',
  'tencent-bangkok': 'Bangkok, Thailand',
  'ec2-ap-southeast-1': 'Singapore',
  'gce-asia-southeast2': 'Jakarta, Indonesia',
  'ec2-ap-east-1': 'Hong Kong, China',
  'gce-asia-east1': 'Taiwan',
  'ec2-ap-northeast-2': 'Seoul, South Korea',
  'ec2-ap-northeast-1': 'Tokyo, Japan',
  'ec2-ap-northeast-3': 'Osaka, Japan',
  'ec2-ap-southeast-2': 'Sydney, Australia',
  'azure-australia-southeast': 'Melbourne, Australia',
  'ec2-us-east-1-bos': 'Boston, Massachusetts, USA',
  'ec2-us-east-1-dfw': 'Dallas, Texas, USA',
  'ec2-us-east-1-mia': 'Miami, Florida, USA',
  'ec2-us-east-1-nyc': 'New York City, New York, USA',
  'ec2-us-west-2-lax': 'Los Angeles, California, USA',
  'ec2-us-west-2-sea': 'Seattle, Washington, USA',
  'ec2-us-west-2-pdx': 'Portland, Oregon, USA',
}

export const NAMES_TO_CODE = {
  VIRGINIA: 'ec2-us-east-1',
  SALT_LAKE_CITY: 'gce-us-west3',
  CALIFORNIA: 'ec2-us-west-1',
  TORONTO: 'ec2-ca-central-1',
  SAO_PAULO: 'ec2-sa-east-1',
  IRELAND: 'ec2-eu-west-1',
  LONDON: 'London_EC2',
  PARIS: 'ec2-eu-west-3',
  AMSTERDAM: 'gce-europe-west4',
  FRANKFURT: 'ec2-eu-central-1',
  MILAN: 'ec2-eu-south-1',
  STOCKHOLM: 'ec2-eu-north-1',
  CAPE_TOWN: 'ec2-af-south-1',
  BAHRAIN: 'ec2-me-south-1',
  MUMBAI: 'ap-south-1',
  BANGKOK: 'tencent-bangkok',
  SINGAPORE: 'ec2-ap-southeast-1',
  Jakarta: 'gce-asia-southeast2',
  HONG_KONG: 'ec2-ap-east-1',
  TAIWAN: 'gce-asia-east1',
  SEOUL: 'ec2-ap-northeast-2',
  TOKYO: 'ec2-ap-northeast-1',
  OSAKA: 'ec2-ap-northeast-3',
  SYDNEY: 'ec2-ap-southeast-2',
  MELBOURNE: 'azure-australia-southeast',
  BOSTON: 'ec2-us-east-1-bos',
  DALLAS: 'ec2-us-east-1-dfw',
  MIAMI: 'ec2-us-east-1-mia',
  NEW_YORK_CITY: 'ec2-us-east-1-nyc',
  LOS_ANGELES: 'ec2-us-west-2-lax',
  SEATTLE: 'ec2-us-west-2-sea',
  PORTlAND: 'ec2-us-west-2-pdx'
}