version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "performance-data-handler"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-k2ji4oitdt85"
s3_prefix = "performance-data-handler"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "DatabaseName=\"TEST1\" DatabaseUsername=\"TEST2\" DatabasePassword=\"Test3\" DatabaseHostname=\"TEST4\""
image_repositories = []
confirm_changeset = true
