AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
# More info about Globals: <https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst>
Globals:
  Function:
    Timeout: 30 # we can set default timeout of all lambda functions here

Resources:

  PerformanceMonitoringApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
  
  PerformanceDataSqs:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 65 # should be greater that lambda timeout

  SqsDataProducer:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      MemorySize: 128
      Environment:
        Variables:
          SQS_URL: !Ref PerformanceDataSqs  # Gets SQS Queue URL 
      Events:
        PerformanceMonitoringApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId:
              Ref: PerformanceMonitoringApi
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./sqs-data-producer
      Dockerfile: Dockerfile
  
  SqsDataConsumer:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 60 #manually overriding function timeout
      Events:
        SqsDataConsumerInvoker:
          Type: SQS
          Properties:
            Queue: !GetAtt Lambda2Sqs.Arn
            BatchSize: 1
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./lambda-2
      Dockerfile: Dockerfile