name: Heroku Deploy

on:
  push:
    branches:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: swishjam-app
          heroku_email: collin.thomas.schneider@swishjam.com
          branch: v2
          appdir: ./backend